format = """
[│](bold purple)$directory$nodejs$golang$python$git_branch$git_status
[└>](bold purple) """

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[package]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = " "
format = '[$symbol]($style)'

[golang]
symbol = " "
format = '[$symbol]($style)'

[nodejs]
symbol = " "
format = '[$symbol]($style)'
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx", "jsx"]
