format = """
[│](bold purple)$directory$package
[│](bold purple)$git_branch$git_status
[└─>](purple) """

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[golang]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[nodejs]
format = '\[[$symbol$version]($style)\]'
